# $OpenBSD$

V =		2.1.7
COMMENT =	tools collection

DISTNAME =	ohtools-${V}
CATEGORIES =	sysutils

HOMEPAGE =	https://github.com/aharri/ohtools

# ISC
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MASTER_SITES = http://openbsd.fi/dist/

RUN_DEPENDS =	graphics/jhead
NO_BUILD =	Yes
PKG_ARCH =	*
DESTDIRNAME =

.include <bsd.port.mk>
